import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">Hello world!</h1>
      <br />
      <Link href="/todos">
        <a>go to todos</a>
      </Link>
      <br />
      <Link href="/about">
        <a>go to about</a>
      </Link>
    </div>
  );
};

export default Home;
